# Generated by Django 5.1.3 on 2024-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
